/**
 * Optional: self-host the Khmer web fonts instead of loading them from Google.
 *
 *   npm run fonts:download
 *
 * Useful when guests are on networks where fonts.googleapis.com is slow or
 * blocked. Once ./public/fonts/fonts.css exists the app uses it automatically.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const FAMILIES = [
  "Noto+Serif+Khmer:wght@400;500;600;700",
  "Noto+Sans+Khmer:wght@300;400;500;600",
  "Cormorant+Garamond:ital,wght@0,400;0,600;1,400",
];

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const outDir = path.join(process.cwd(), "public", "fonts");
mkdirSync(outDir, { recursive: true });

let bundle = "/* Self-hosted web fonts — generated by scripts/download-fonts.mjs */\n";
let count = 0;

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family}&display=swap`;
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());

  const rewritten = await replaceAsync(css, /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g, async (_m, fontUrl) => {
    const filename = fontUrl.split("/").slice(-2).join("-").replace(/[^\w.-]/g, "");
    const data = Buffer.from(await fetch(fontUrl).then((r) => r.arrayBuffer()));
    writeFileSync(path.join(outDir, filename), data);
    count += 1;
    return `url(/fonts/${filename})`;
  });

  bundle += rewritten + "\n";
}

writeFileSync(path.join(outDir, "fonts.css"), bundle);
console.log(`✔ downloaded ${count} font files into public/fonts`);

async function replaceAsync(input, regex, replacer) {
  const promises = [];
  input.replace(regex, (...args) => {
    promises.push(replacer(...args));
    return "";
  });
  const values = await Promise.all(promises);
  return input.replace(regex, () => values.shift());
}
